// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { StoreHooks, StoreHooksTableId } from "./StoreHooks.sol";
import { Tables, TablesData, TablesTableId } from "./Tables.sol";
import { ResourceIds, ResourceIdsTableId } from "./ResourceIds.sol";
import { Hooks } from "./Hooks.sol";
